
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: compiled_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: compiled_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: compiled_production
  username: compiled
  password: <%= ENV["COMPILED_DATABASE_PASSWORD"] %>
